### ISSUE TITLE
node SyntaxError: expected indent but found await

### ISSUE THREAD

**Issue by vvirtues** [OpenAsar/arrpc#1]
Do I add an indent?
![firefox_wAtJQMIxp8](https://user-images.githubusercontent.com/81705406/202871033-61581897-be9b-482c-9963-4336c3c52468.png)

**Comment by CanadaHonk** [comment]
> use new Node

What Node version?

**Comment by vvirtues** [comment]
12.22.1

**Comment by CanadaHonk** [comment]
> use new Node
