### ISSUE TITLE
Browser extension/userscript for bridge

### ISSUE THREAD

**Issue by rollingmoai** [OpenAsar/arrpc#14]
Possible? The obvious advantage being that it is convenient and you don't need to have Node installed (or maybe you can provide prebuilt binaries)

**Comment by CanadaHonk** [comment]
Not possible, browser extensions can't run native things. It would be possible to run the client/mod everytime via an extension without having to use the console.

**Comment by rollingmoai** [comment]
> It would be possible to run the client/mod everytime via an extension without having to use the console.

Or a userscript, that would be better

**Comment by rollingmoai** [comment]
Both of them doesn't seem to work

**Comment by CanadaHonk** [comment]
Console output/errors/etc?

**Comment by rollingmoai** [comment]
Here's for the userscript:
![image](https://user-images.githubusercontent.com/75471378/203886160-b778d380-2683-4ec8-83ab-bfcc98d3cd6d.png)

And here is for the extension:
![image](https://user-images.githubusercontent.com/75471378/203886345-77a1bfef-1af4-472a-84fd-63df8c4ece9a.png)

**Comment by Scrxtchy** [comment]
With a little bit of work you can run the server under the browser, is this feature still desired?
<img width="539" height="491" alt="Image" src="https://github.com/user-attachments/assets/9083aa7c-73d5-4bd8-84a4-719bf582af2f" />
