### ISSUE TITLE
Is Linux not supported yet... ?

### ISSUE THREAD

**Issue by Impeta** [OpenAsar/arrpc#22]
![Screenshot_20230118_094232](https://user-images.githubusercontent.com/105376276/213174382-abcf5d5c-57c5-4c01-9bec-85ca325f7538.png)

Based on that one red-colored report there, it seems to say such, though I haven't truly tried any RPC-compliant software yet. I'm on ArmCord.

**Comment by CanadaHonk** [comment]
You shouldn't be using the Vencord plugin, arRPC is built into Armcord and you should get support in the Armcord discord instead.
