### ISSUE TITLE
How to make prebuilt packages [NOT AN ISSUE]

### ISSUE THREAD

**Issue by cradio** [OpenAsar/arrpc#25]
So ArRPC is a real lifesaver for me as I use Vencord. But it requires node environment and I can't add it to windows autostart (and also obligated to have console window all the time). You may have other reasons to have prebuilt binaries, but whatever

1. Install `esbuild` and `pkg`:
```bash
npm i -g esbuild pkg
```
2. Wrap that async statement in async function and call it
```diff

import * as Bridge from './bridge.js';
import Server from './server.js';

- const server = await new Server();

- server.on('activity', data => Bridge.send(data));
+ async function main() {
+     const server = await new Server();
+     server.on('activity', data => Bridge.send(data));
+ }

+ main();
```
3. Bundle to single file via esbuild (node ≤ 18, node19 is not supported yet by `pkg`):
```bash
esbuild --bundle --platform=node --target=node18 --outdir=dist .\src\index.js
```
4. Build executable:
```bash
pkg -t node18-win-x64 -o arrpc  .\dist\index.js #Windows amd64,  Node 18.x
pkg -t node18-linux-x64 -o arrpc  .\dist\index.js #Linux amd64, Node 18.x
pkg -t node18-macos-x64 -o arrpc  .\dist\index.js #MacOS amd64, Node 18.x
```
5. Voila!
![Screenshot guyes look](https://user-images.githubusercontent.com/38406005/222386974-be029dff-2989-4c6e-85cb-39e4f5514030.png)

6. It works perfectly fine (for now), but might require further testing

**Comment by joulev** [comment]
Thanks, this worked beautifully!
