### ISSUE TITLE
[Enchantment] add ways to enter custom activity in console

### ISSUE THREAD

**Issue by yt6983138** [OpenAsar/arrpc#29]
Maybe add a way to enter a custom activity in console, example below:
```
[arRPC > bridge] web connected
custom-activity on
[arRPC] custom activity is now on
custom-activity set name a-sus-game-or-smth-idk-and-this-is-a-long-name-lmao
[arRPC] name of custom activity has been set to a-sus-game-or-smth-idk-and-this-is-a-long-name-lmao
custom-activity set icon [base64 encoded image here or imgur link]
[arRPC] icon of custom activity has been set
custom-activity reset time
[arRPC] time has been reset to 00:00
...
```
or add a configuration file to make custom activity
i know it is possible by modifying [src](https://github.com/OpenAsar/arrpc/tree/main/src)/[process](https://github.com/OpenAsar/arrpc/tree/main/src/process)/detectable.json to add a process and enter a custom description or smth.

**Comment by CanadaHonk** [comment]
Use a custom RPC program.
