### ISSUE TITLE
pin package-lock.json

### ISSUE THREAD

**Issue by NotAShelf** [OpenAsar/arrpc#31]
Hey! I'm trying to package arrpc for NixOS, however, packaging node applications for nix benefits *heavily* from vendored package-lock.json

Any chance it could be included in the repo for packaging purposes?

**Comment by CanadaHonk** [comment]
The only dependency is `ws` which will not get any new breaking changes so not needed?

**Comment by NotAShelf** [comment]
It is a part of Nix's packaging idiom. To be able to build a node package (which arrpc classifies as) we need a vendored package lock.

**Comment by CanadaHonk** [comment]
Added :)

**Comment by NotAShelf** [comment]
Appreciated, thank you!
