### ISSUE TITLE
Please add the ability to disable logging

### ISSUE THREAD

**Issue by Vendicated** [OpenAsar/arrpc#34]
arrpc is absolutely spamming the console

![image](https://github.com/OpenAsar/arrpc/assets/45497981/07e5f57d-9acc-4094-9090-012732e2e5f7)

This is not a problem when running it manually, but when embedded as library, this is a nuisance. Please add the ability to suppress logging

**Comment by CanadaHonk** [comment]
Disabled (mostly) unneeded logging behind `ARRPC_DEBUG` env variable.
