### ISSUE TITLE
not working

### ISSUE THREAD

**Issue by ayaanmd100** [OpenAsar/arrpc#42]
Even though its running, the Vencord Web Client says it cannot connect to it
![image](https://github.com/OpenAsar/arrpc/assets/109349651/9338474e-2b03-4c89-bf09-870c8d4e4d44)
![image](https://github.com/OpenAsar/arrpc/assets/109349651/a297f919-a14c-4c3e-a8a3-546c10be5d71)

**Comment by CanadaHonk** [comment]
Ensure the server is running before opening Discord/enabling the plugin. Screenshot the browser console.

**Comment by CanadaHonk** [comment]
Please use [the Discord server](https://discord.com/invite/neMncS2) for support, not GitHub issues for easier communication.
