### ISSUE TITLE
music bee status does not stop / clear when pausing music (works on normal discord client)

### ISSUE THREAD

**Issue by Benzeel** [OpenAsar/arrpc#43]
i use vesktop, but i don't think that should have anything to do with it, since it seems to work in every other way, and WOULD clear on SOME occasions, although very inconsistent and not very commonly. the status can change to something else but just doesn't clear.

im using the discordbee plugin with musicbee to get the custom rpc for it to work.

looking through dev tools in the console, im seeing no errors. related to arrpc

again, it works like normal if running normal desktop discord. (i also dont think this issue is related to vesktop, though im not 100% sure)

regardless im leaving this here incase it isnt in fact a vesktop spesific issue.

**Comment by CanadaHonk** [comment]
Please use [the Discord server](https://discord.com/invite/neMncS2) for support, not GitHub issues for easier communication.
