### ISSUE TITLE
Wrong game

### ISSUE THREAD

**Issue by pwsh7** [OpenAsar/arrpc#53]
I was only playing Roblox but it says  im playing a game called Last Man Standing while i was not playing anything else except Roblox.
Terminal logs and in-app view is included below.

![image](https://github.com/OpenAsar/arrpc/assets/84739184/46cf3f13-1649-4f7a-9308-ae68e948a42e)
![image](https://github.com/OpenAsar/arrpc/assets/84739184/d23d3e24-2941-4775-ab70-59afb8565322)

**Comment by femboyjophiel** [comment]
same issue lol

**Comment by CanadaHonk** [comment]
Bug in Discord's game DB. I'll update later and see if they fixed it.

**Comment by CanadaHonk** [comment]
It was updated and should have been fixed.
