### ISSUE TITLE
Not detecting games with rpc

### ISSUE THREAD

**Issue by twinflac** [OpenAsar/arrpc#58]
![scr2023-11-27-00:18:36](https://github.com/OpenAsar/arrpc/assets/87523240/ab93ae5e-4d1e-447e-8799-b7dcf0dbdcc9)

os: gnu/linux
wm: sway
node: 21.2.0

**Comment by CanadaHonk** [comment]
Need more info, what games, etc

**Comment by twinflac** [comment]
factorio, faster than light

**Comment by CanadaHonk** [comment]
They aren't in [Discord's game DB](https://disgamebrowser.openasar.dev/) so that's expected (for now).

**Comment by twinflac** [comment]
i'm so sorry, not understand this before and ask other thash isue

**Comment by twinflac** [comment]
> They aren't in [Discord's game DB](https://disgamebrowser.openasar.dev/) for Linux so that's expected (for now).

3% of games for linux support this
