### ISSUE TITLE
letting arRPC run in the background on linux

### ISSUE THREAD

**Issue by falcie1337** [OpenAsar/arrpc#68]
i'm currently running endeavouros and i wish there was a way to just let arRPC run in the background instead of having a terminal window open and unusable all the time because it's running node src all the time, is there a way to actually make it just run and let me use my terminal or like, make it be a background daemon or something? i dont know jackshit about nodejs so im sorry about this if it is a stupid question, but i also saw nothing about it in the README so i figured i should ask it here

**Comment by virtuanista** [comment]
Use pm2

**Comment by falcie1337** [comment]
will give a look into it, thanks for the suggestion.
