### ISSUE TITLE
Mark releases using git tags (and maybe GH releases)

### ISSUE THREAD

**Issue by Freso** [OpenAsar/arrpc#72]
It would be helpful for downstream packagers if you would [`git tag`](https://git-scm.com/book/en/v2/Git-Basics-Tagging) releases instead of just marking something as a release by mentioning it in the commit message, since we’d then be able to fetch the git repository based on that tag. Potentially even make [GitHub releases](https://docs.github.com/en/repositories/releasing-projects-on-github) that we’d be able to follow and get notifications for. :)

(E.g., my [AUR package](https://aur.archlinux.org/pkgbase/arrpc) currently [includes the specific git commit for the given release](https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=arrpc&id=0fdba651a46eb63fe570f6de890c72f879603ed0#n5).)

**Comment by CanadaHonk** [comment]
Done from now on, thanks!
