### ISSUE TITLE
arrpc fails to start

### ISSUE THREAD

**Issue by CosmicHeron** [OpenAsar/arrpc#77]
Running into an odd issue, installed Arch on my laptop and while aarpc has been working fine on my desktop it fails to start on the laptop, even when using the same package from the AUR. I have installed [arrpc](https://aur.archlinux.org/packages/arrpc) (tried [arrpc-git](https://aur.archlinux.org/packages/arrpc-git) too, same result), enabled and started the service using `systemctl --user enable --now arrpc.service` and got an error message in Vencord that ARRPC could not be detected. Running `systemctl --user status arrpc.service` return the following:

```
systemctl --user status arrpc.service
× arrpc.service - arRPC Discord RPC daemon
     Loaded: loaded (/usr/lib/systemd/user/arrpc.service; enabled; preset: enabled)
     Active: failed (Result: exit-code) since Mon 2024-04-22 17:36:27 UTC; 1min 35s ago
   Duration: 81ms
    Process: 52163 ExecStart=/usr/bin/arrpc (code=exited, status=1/FAILURE)
   Main PID: 52163 (code=exited, status=1/FAILURE)
        CPU: 80ms

Apr 22 17:36:27 arch systemd[5221]: arrpc.service: Scheduled restart job, restart counter is at 5.
Apr 22 17:36:27 arch systemd[5221]: arrpc.service: Start request repeated too quickly.
Apr 22 17:36:27 arch systemd[5221]: arrpc.service: Failed with result 'exit-code'.
Apr 22 17:36:27 arch systemd[5221]: Failed to start arRPC Discord RPC daemon.
```

And here's the full journalctl log of it failing to start:

```
Apr 22 17:36:26 arch systemd[5221]: Started arRPC Discord RPC daemon.
Apr 22 17:36:26 arch arrpc[51829]: Pkg: Error reading from file.
Apr 22 17:36:26 arch systemd[5221]: arrpc.service: Main process exited, code=exited, status=1/FAILURE
Apr 22 17:36:26 arch systemd[5221]: arrpc.service: Failed with result 'exit-code'.
Apr 22 17:36:26 arch systemd[5221]: arrpc.service: Scheduled restart job, restart counter is at 1.
Apr 22 17:36:26 arch systemd[5221]: Started arRPC Discord RPC daemon.
Apr 22 17:36:26 arch arrpc[52141]: Pkg: Error reading from file.
Apr 22 17:36:26 arch systemd[5221]: arrpc.service: Main process exited, code=exited, status=1/FAILURE
Apr 22 17:36:26 arch systemd[5221]: arrpc.service: Failed with result 'exit-code'.
Apr 22 17:36:26 arch systemd[5221]: arrpc.service: Scheduled restart job, restart counter is at 2.
Apr 22 17:36:26 arch systemd[5221]: Started arRPC Discord RPC daemon.
Apr 22 17:36:26 arch arrpc[52149]: Pkg: Error reading from file.
Apr 22 17:36:26 arch systemd[5221]: arrpc.service: Main process exited, code=exited, status=1/FAILURE
Apr 22 17:36:26 arch systemd[5221]: arrpc.service: Failed with result 'exit-code'.
Apr 22 17:36:27 arch systemd[5221]: arrpc.service: Scheduled restart job, restart counter is at 3.
Apr 22 17:36:27 arch systemd[5221]: Started arRPC Discord RPC daemon.
Apr 22 17:36:27 arch arrpc[52156]: Pkg: Error reading from file.
Apr 22 17:36:27 arch systemd[5221]: arrpc.service: Main process exited, code=exited, status=1/FAILURE
Apr 22 17:36:27 arch systemd[5221]: arrpc.service: Failed with result 'exit-code'.
Apr 22 17:36:27 arch systemd[5221]: arrpc.service: Scheduled restart job, restart counter is at 4.
Apr 22 17:36:27 arch systemd[5221]: Started arRPC Discord RPC daemon.
Apr 22 17:36:27 arch arrpc[52163]: Pkg: Error reading from file.
Apr 22 17:36:27 arch systemd[5221]: arrpc.service: Main process exited, code=exited, status=1/FAILURE
Apr 22 17:36:27 arch systemd[5221]: arrpc.service: Failed with result 'exit-code'.
Apr 22 17:36:27 arch systemd[5221]: arrpc.service: Scheduled restart job, restart counter is at 5.
Apr 22 17:36:27 arch systemd[5221]: arrpc.service: Start request repeated too quickly.
Apr 22 17:36:27 arch systemd[5221]: arrpc.service: Failed with result 'exit-code'.
Apr 22 17:36:27 arch systemd[5221]: Failed to start arRPC Discord RPC daemon.
```

I'm not sure what's causing this, especially since it works out of the box on my PC.

**Comment by CanadaHonk** [comment]
The AUR package is unofficial and makes large changes which are unsupported.

**Comment by rgcv** [comment]
I'm sorry to bump this issue, but what changes could you possibly be referring to?  All I see is an additional systemd unit file.  That is excluding the git package, which even then only seems to define a couple of build flags and a minor patch that _shouldn't_ (though I won't risk saying it certainly wouldn't) change anything behaviorally.

**Comment by CosmicHeron** [comment]
The AUR release that was broken had an extra patch file which, I assume, was causing problems. It has since been removed in the fixed versions and the PKGBUILD will now just build the package without any modification.

**Comment by rgcv** [comment]
> The AUR release that was broken had an extra patch file which, I assume, was causing problems. It has since been removed in the fixed versions and the PKGBUILD will now just build the package without any modification.

Yes, that seems to be the case for `arrpc-git`, though I can't see that patch file in the main package.  Granted, it used to build the project much like the git package is currently still specced to do so minus the patch the latter still employs.  The git package is probably still broken.

Even then, I don't see that many a change going through the changelog for the AUR package.  That just confused me a bit, that's all.
