### ISSUE TITLE
server: dismiss rpc on app disconnect

### ISSUE THREAD

**Issue by CanadaHonk** [OpenAsar/arrpc#8]
currently stays stuck on when an app disconnects

**Comment by CanadaHonk** [comment]
done in 512e880!

**Comment by TheJAXi** [comment]
Not to open up an old issue, but this still happens. Shows (in my case) Playnite even after closing the game, and the actual app (Playnite). It only updates the game when launching another, but closing game doesn't return it to the "idle" state.
