### ISSUE TITLE
SyntaxError: Unexpected Identifier `assert`

### ISSUE THREAD

**Issue by IntNinja** [OpenAsar/arrpc#80]
```file:///home/intninja/Documents/arrpc/src/process/index.js:4
import DetectableDB from "./detectable.json" assert { type: "json" };
                                             ^^^^^^

SyntaxError: Unexpected identifier 'assert'
    at compileSourceTextModule (node:internal/modules/esm/utils:337:16)
    at ModuleLoader.moduleStrategy (node:internal/modules/esm/translators:166:18)
    at callTranslator (node:internal/modules/esm/loader:416:14)
    at ModuleLoader.moduleProvider (node:internal/modules/esm/loader:422:30)

Node.js v22.0.0
```

when running `node src`

**Comment by re7gog** [comment]
Same error

**Comment by IntNinja** [comment]
> Same error

Seems to be error specifically on linux distros

**Comment by re7gog** [comment]
> > Same error
> 
> Seems to be error specifically on linux distros

I'm on Windows 11

**Comment by Saarker** [comment]
Ran into the same issue trying to fix [this one](https://github.com/OpenAsar/arrpc/issues/81), make sure to specifically switch to NodeJS 18 through NVM.

**Comment by kmoschcau** [comment]
Hi. Why was this closed when the README says

> Have latest (>=18) Node installed

Either this should be fixed to work with node 22 and higher or the README should be updated.
