### ISSUE TITLE
SyntaxError: Unexpected reserved word

### ISSUE THREAD

**Issue by TheAceburn** [OpenAsar/arrpc#81]
```
file:///home/cynderace/arRPC/src/index.js:11
const server = await new Server();
               ^^^^^

SyntaxError: Unexpected reserved word
    at Loader.moduleStrategy (internal/modules/esm/translators.js:133:18)
    at async link (internal/modules/esm/module_job.js:42:21)
```

**Comment by Saarker** [comment]
Was having the same issue, using specifically NodeJS 18 seems to fix the issue, using an older version will cause this issue, using a newer version will cause [this](https://github.com/OpenAsar/arrpc/issues/80) issue. Make sure to switch/install versions through NVM and not your packet manager. 
`nvm install 18
nvm use 18`
